# docker-compose.yml
services:
  fragments:
    # dnglglmm/fragments:latest
    image: ${DOCKER_REPO}:${DOCKER_TAG}
    init: true
    ports:
      - '80:8080'
    environment:
      - NODE_ENV=development
      - HTPASSWD_FILE=tests/.htpasswd
      # Our API will be running on http://localhost:8080
      - API_URL=http://localhost:8080
